spring:
  cloud:
    gateway:
      routes:
        - id: ms-catalogos
          uri: http://${CATALOGOS_HOST:ms-catalogos}:${CATALOGOS_PORT:8081}
          predicates:
            - Path=/api/catalogos/**
          filters:
            - StripPrefix=2

        - id: ms-solicitudes
          uri: http://${SOLICITUDES_HOST:ms-solicitudes}:${SOLICITUDES_PORT:8082}
          predicates:
            - Path=/api/solicitudes/**
          filters:
            - StripPrefix=2

        - id: ms-operaciones
          uri: http://${OPERACIONES_HOST:ms-operaciones}:${OPERACIONES_PORT:8083}
          predicates:
            - Path=/api/operaciones/**
          filters:
            - StripPrefix=2
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8084/realms/tpi-backend

# Propiedad para leer en SecurityConfig si quisiéramos desactivar seguridad
gateway:
  security:
    enabled: true