server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # CONFIGURACIÓN CORS CENTRALIZADA
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*" # Permite cualquier origen de forma segura con credenciales
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus