server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway

springdoc:
  swagger-ui:
    path: /swagger

tpi:
  gateway:
    services:
      catalogos:
        uri: http://${CATALOGOS_HOST:ms-catalogos}:${CATALOGOS_PORT:8080}
      solicitudes:
        uri: http://${SOLICITUDES_HOST:ms-solicitudes}:${SOLICITUDES_PORT:8080}
      operaciones:
        uri: http://${OPERACIONES_HOST:ms-operaciones}:${OPERACIONES_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
