server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # CONFIGURACIÓN CORS CENTRALIZADA
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*" # Permite cualquier origen de forma segura con credenciales
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: ms-catalogos
          uri: http://${CATALOGOS_HOST:localhost}:${CATALOGOS_PORT:8081}
          predicates:
            - Path=/api/catalogos/**
          filters:
            - StripPrefix=2

        - id: ms-solicitudes
          uri: http://${SOLICITUDES_HOST:localhost}:${SOLICITUDES_PORT:8082}
          predicates:
            - Path=/api/solicitudes/**
          filters:
            - StripPrefix=2

        - id: ms-operaciones
          uri: http://${OPERACIONES_HOST:localhost}:${OPERACIONES_PORT:8083}
          predicates:
            - Path=/api/operaciones/**
          filters:
            - StripPrefix=2

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus