spring:
  cloud:
    gateway:
      routes:
        - id: ms-catalogos
          uri: lb://ms-catalogos # Load balancing con el nombre del servicio Docker
          predicates:
            - Path=/api/catalogos/**
          filters:
            - StripPrefix=1
        - id: ms-solicitudes
          uri: lb://ms-solicitudes
          predicates:
            - Path=/api/solicitudes/**
          filters:
            - StripPrefix=1
        - id: ms-operaciones
          uri: lb://ms-operaciones
          predicates:
            - Path=/api/operaciones/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          # URL del emisor de Keycloak
          issuer-uri: http://keycloak:8084/realms/master
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: api-gateway