spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/operaciones
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  security:
    enabled: false
    #oauth2:
    #  resourceserver:
    #    jwt:
    #      issuer-uri: http://keycloak:8084/realms/master

# Configuración de comunicación con otros microservicios (Docker network)
ms-catalogos:
  url: http://ms-catalogos:8081

# Configuración de OSRM para cálculo de rutas
osrm:
  url: http://osrm-backend:5000

server:
  port: 8083
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: ms-operaciones
