server:
  port: 8083

spring:
  application:
    name: ms-operaciones
  datasource:
    url: jdbc:postgresql://postgres:5432/operaciones
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: public
      hibernate.format_sql: true
  flyway:
    enabled: false
    locations: classpath:db/migration

springdoc:
  swagger-ui:
    path: /swagger

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: always
