server:
  port: 8083
  forward-headers-strategy: framework


spring:
  application:
    name: ms-operaciones
  datasource:
    url: jdbc:postgresql://localhost:5433/operaciones
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: always
springdoc:
  swagger-ui:
    path: /swagger-ui.html
