spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/operaciones
  jpa:
    hibernate:
      ddl-auto: update

# AÑADIDO: Sobreescribimos las URLs para que funcionen dentro de la red de Docker
ms-catalogos:
  url: http://ms-catalogos:8081
osrm:
  url: http://osrm-backend:5000