services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks: [tpi]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  ms-catalogos:
    build: ../ms-catalogos
    image: tpi/ms-catalogos:0.1.0
    container_name: ms-catalogos
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_FLYWAY_ENABLED=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 45s
    depends_on:
      postgres:
        condition: service_healthy
    networks: [tpi]

  ms-solicitudes:
    build: ../ms-solicitudes
    image: tpi/ms-solicitudes:0.1.0
    container_name: ms-solicitudes
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_FLYWAY_ENABLED=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 45s
    depends_on:
      postgres:
        condition: service_healthy
    networks: [tpi]

  ms-operaciones:
    build: ../ms-operaciones
    image: tpi/ms-operaciones:0.1.0
    container_name: ms-operaciones
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_FLYWAY_ENABLED=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 45s
    depends_on:
      postgres:
        condition: service_healthy
    networks: [tpi]

  api-gateway:
    build: ../api-gateway
    image: tpi/api-gateway:0.1.0
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_FLYWAY_ENABLED=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    depends_on:
      ms-catalogos:
        condition: service_healthy
      ms-solicitudes:
        condition: service_healthy
      ms-operaciones:
        condition: service_healthy
    networks: [tpi]

  # keycloak (stub) — lo dejamos listo pero comentado hasta Iteración de seguridad:
  # keycloak:
  #   image: quay.io/keycloak/keycloak:24.0
  #   container_name: keycloak
  #   command: ["start-dev","--http-port=8084"]
  #   environment:
  #     - KEYCLOAK_ADMIN=admin
  #     - KEYCLOAK_ADMIN_PASSWORD=admin
  #   ports: ["8084:8084"]
  #   networks: [tpi]

networks:
  tpi: {}

volumes:
  pgdata: {}
