spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/catalogos
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update # Hibernate creará/actualizará las tablas
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    enabled: false
    basic:
      enabled: false
    oauth2:
      resourceserver:
        jwt:
          enabled: false
server:
  port: 8081 # Puerto interno para el microservicio
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: ms-catalogos