server:
  port: 8081

spring:
  application:
    name: ms-catalogos
  datasource:
    url: jdbc:postgresql://postgres:5432/catalogos
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: public
      hibernate.format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: true
