server:
  port: 8082
  forward-headers-strategy: framework

spring:
  application:
    name: ms-solicitudes
  datasource:
    url: jdbc:postgresql://localhost:5433/solicitudes
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8084/realms/tpi-backend
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: always